version: '3.4'

services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: src/Lab9/Backend/Presentation/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"

  lab9.database:
    image: postgres:latest
    environment:
     - POSTGRES_DB=lab9_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/products-db:/var/lib/postgresql/data
    ports:
     - 5432:5432    